openapi: 3.0.2
info:
  title: Strapi personalization Plugin
  version: 1.0.0
servers:
  - url: http://localhost:1337
    description: Local server
externalDocs:
  url: https://docs.strapi.io
  description: Strapi documentation
paths:
  /personalization/variations:
    get:
      tags:
        - Locales
      description: List variations used by the app
      responses:
        200:
          description: A list of variations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/variation'
    post:
      tags:
        - Locales
      description: Create a variation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/variationInputCreate'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/variation'
  /personalization/variations/{id}:
    put:
      tags:
        - Locales
      description: Update the name of a variation
      parameters:
        - $ref: '#/components/parameters/variation-id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/variationInputUpdate'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/variation'
  /personalization/content-manager/actions/get-non-personalized-fields:
    post:
      tags:
        - Content-Manager
      description: Return the non personalized fields of a related entity in order to pre-fill the creation form of a related entity.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getNonLocalizedFieldsInput'
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  nonLocalizedFields:
                    type: object
                  personalizations:
                    description: All related entities id and variation
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: '#/components/schemas/id'
                          description: Id of this related entity
                        variation:
                          type: string
                          description: Code of the variation of this related entity

components:
  schemas:
    id:
      oneOf:
        - type: string
        - type: integer

    variationInputCreate:
      type: object
      required:
        - code
        - isDefault
      properties:
        name:
          type: string
          description: Name of the variation
        code:
          type: string
          description: ISO code of the variation
        isDefault:
          type: boolean
          description: Set default variation (ignored if set to false)

    variationInputUpdate:
      type: object
      properties:
        name:
          type: string
          description: Name of the variation
        isDefault:
          type: boolean
          description: Set default variation (ignored if set to false)

    getNonLocalizedFieldsInput:
      type: object
      required:
        - model
        - id
        - variation
      properties:
        model:
          type: string
          description: Model of the entity
        id:
          $ref: '#/components/schemas/id'
          description: Id of an entity related to the one that will be created
        variation:
          type: string
          description: The variation of the entity that will be pre-filled with the non personalized fields this route returns

    variation:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
        name:
          type: string
          description: Name of the variation
        code:
          type: string
          description: ISO code of the variation
        isDefault:
          type: boolean
          description: Is the default variation

    iso-variation:
      type: object
      properties:
        name:
          type: string
          description: Name of the variation
        code:
          type: string
          description: ISO code of the variation

  parameters:
    variation-id:
      in: path
      name: id
      schema:
        type: string
      required: true
      description: Locale id

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []
